"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dataRoutes = void 0;
const suggest_1 = require("./suggest");
const alator_1 = require("./alator");
const antevorta_1 = require("./antevorta");
const risk_1 = require("./risk");
const user_1 = require("./user");
const dataRoutes = (fastify, _opts, done) => {
    fastify.get('/suggest', { schema: suggest_1.schema }, (0, suggest_1.handler)(fastify));
    fastify.post('/backtest', { schema: alator_1.schema }, (0, alator_1.handler)(fastify));
    fastify.post('/incomesim', { schema: antevorta_1.schema }, (0, antevorta_1.handler)(fastify));
    fastify.get('/riskattribution', { schema: risk_1.schema }, (0, risk_1.handler)(fastify));
    fastify.get('/create', { schema: user_1.createSchema }, (0, user_1.createHandler)(fastify));
    fastify.post('/login', { schema: user_1.loginSchema }, (0, user_1.loginHandler)(fastify));
    fastify.get('/logout', { schema: user_1.logoutSchema }, (0, user_1.logoutHandler)(fastify));
    fastify.delete('/portfolio', { schema: user_1.removePortfolioSchema }, (0, user_1.removePortfolioHandler)(fastify));
    fastify.post('/portfolio', { schema: user_1.addPortfolioSchema }, (0, user_1.addPortfolioHandler)(fastify));
    fastify.delete('/plan', { schema: user_1.removeFinancialPlanSchema }, (0, user_1.removeFinancialPlanHandler)(fastify));
    fastify.post('/plan', { schema: user_1.addFinancialPlanSchema }, (0, user_1.addFinancialPlanHandler)(fastify));
    fastify.get('/userstate', { schema: user_1.getUserStateSchema }, (0, user_1.getUserStateHandler)(fastify));
    done();
};
exports.dataRoutes = dataRoutes;
